import json
import subprocess
from pathlib import Path

import pytest
from inventory import build_inventory, list_source_files, main


def _git(repo: Path, *args: str) -> None:
    subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        capture_output=True,
    )


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "test@example.com")
    _git(tmp_path, "config", "user.name", "Test")

    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "calc.py").write_text("def net(x):\n    return x\n")
    (tmp_path / "src" / "gen.py").write_text(
        "# Code generated by tool. DO NOT EDIT.\nA = 1\n"
    )
    (tmp_path / "src" / "long.py").write_text("x = 1\n" * 900)
    (tmp_path / "src" / "blob.py").write_bytes(b"\xff\xfe\x00\x01")
    (tmp_path / "README.md").write_text("# readme\n")

    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "test_calc.py").write_text("def test_x():\n    pass\n")

    (tmp_path / "vendor").mkdir()
    (tmp_path / "vendor" / "lib.py").write_text("B = 2\n")

    # A dangling symlink (target never existed) and a file that is tracked
    # but has since been deleted from disk without `git rm` -- both everyday
    # mid-rebase states, and both must not crash the inventory.
    (tmp_path / "src" / "dangling.py").symlink_to(
        tmp_path / "src" / "does-not-exist.py"
    )
    (tmp_path / "src" / "ghost.py").write_text("C = 3\n")

    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-q", "-m", "fixture")

    (tmp_path / "src" / "ghost.py").unlink()

    return tmp_path


def test_list_source_files_returns_tracked_paths(repo: Path):
    paths = list_source_files(repo)
    assert "src/calc.py" in paths
    assert "README.md" in paths


def test_build_inventory_keeps_ordinary_source(repo: Path):
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/calc.py" in kept


def test_build_inventory_drops_generated_tests_vendor_and_non_source(repo: Path):
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/gen.py" not in kept
    assert "tests/test_calc.py" not in kept
    assert "vendor/lib.py" not in kept
    assert "README.md" not in kept


def test_build_inventory_counts_each_exclusion_reason(repo: Path):
    inventory = build_inventory(repo)
    assert inventory["excluded"]["generated"] == 1
    assert inventory["excluded"]["path_rule"] == 2
    assert inventory["excluded"]["unsupported_extension"] == 1


def test_build_inventory_splits_unreadable_files_by_cause(repo: Path):
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/blob.py" not in kept
    assert "src/dangling.py" not in kept
    assert "src/ghost.py" not in kept
    # dangling.py (dangling symlink) and ghost.py (tracked but deleted from
    # disk) are both a FileNotFoundError -> "missing". blob.py is a bad
    # encoding -> "undecodable". Neither triggers a permission error here.
    assert inventory["excluded"]["missing"] == 2
    assert inventory["excluded"]["undecodable"] == 1
    assert inventory["excluded"]["permission_denied"] == 0
    assert inventory["excluded"]["path_rule"] == 2
    assert sorted(inventory["excluded_paths"]["missing"]) == [
        "src/dangling.py",
        "src/ghost.py",
    ]
    assert inventory["excluded_paths"]["undecodable"] == ["src/blob.py"]
    assert inventory["excluded_paths"]["permission_denied"] == []


def test_build_inventory_tracks_unsupported_extension_histogram(repo: Path):
    inventory = build_inventory(repo)
    assert inventory["unsupported_extensions"] == {".md": 1}


def test_build_inventory_records_generated_paths(repo: Path):
    inventory = build_inventory(repo)
    assert inventory["excluded_paths"]["generated"] == ["src/gen.py"]


def test_build_inventory_counts_untracked_source_files(repo: Path):
    (repo / "src" / "wip.py").write_text("D = 4\n")
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/wip.py" not in kept
    assert inventory["excluded"]["untracked"] == 1
    assert inventory["excluded_paths"]["untracked"] == ["src/wip.py"]
    # Untracked files must not perturb the tracked-file counters.
    assert inventory["excluded"]["path_rule"] == 2


def test_build_inventory_chunks_long_files(repo: Path):
    inventory = build_inventory(repo)
    entry = next(e for e in inventory["files"] if e["path"] == "src/long.py")
    assert entry["lines"] == 900
    assert entry["chunks"] == [[1, 800], [761, 900]]


def test_build_inventory_records_language(repo: Path):
    inventory = build_inventory(repo)
    entry = next(e for e in inventory["files"] if e["path"] == "src/calc.py")
    assert entry["language"] == "python"


def test_include_tests_keeps_the_test_corpus(repo: Path):
    inventory = build_inventory(repo, include_tests=True)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "tests/test_calc.py" in kept


def test_totals_are_consistent_with_the_file_list(repo: Path):
    # Fixture's only kept files are src/calc.py (2 lines, 1 chunk) and
    # src/long.py (900 lines, chunked as [1, 800] and [761, 900] -- see
    # test_build_inventory_chunks_long_files). Asserted as literal constants,
    # not recomputed from the implementation's own output, so a wrong sum
    # cannot mark its own homework.
    inventory = build_inventory(repo)
    assert inventory["totals"]["files"] == 2
    assert inventory["totals"]["lines"] == 902
    assert inventory["totals"]["chunks"] == 3


def test_cli_writes_json_to_stdout(repo: Path, capsys):
    exit_code = main([str(repo)])
    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out)
    assert isinstance(payload["files"], list)
    assert any(entry["path"] == "src/calc.py" for entry in payload["files"])


def test_cli_include_tests_flag_keeps_the_test_corpus(repo: Path, capsys):
    exit_code = main([str(repo), "--include-tests"])
    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out)
    kept = {entry["path"] for entry in payload["files"]}
    assert "tests/test_calc.py" in kept


def test_cli_rejects_a_path_that_is_not_a_git_repo(tmp_path: Path, capsys):
    exit_code = main([str(tmp_path)])
    assert exit_code == 1
    assert "not a git repository" in capsys.readouterr().err
