import pytest
from inventory import SOURCE_EXTENSIONS, chunk_plan, is_excluded_path, is_generated


def test_known_extensions_map_to_languages():
    assert SOURCE_EXTENSIONS[".cs"] == "csharp"
    assert SOURCE_EXTENSIONS[".php"] == "php"
    assert SOURCE_EXTENSIONS[".py"] == "python"
    assert SOURCE_EXTENSIONS[".ts"] == "typescript"


@pytest.mark.parametrize(
    "head",
    [
        "//------\n// <auto-generated>\n//------\nnamespace X {}",
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x",
        "/* @generated */\nconst a = 1;",
        "# DO NOT EDIT - generated from schema.yaml\nclass A: pass",
    ],
)
def test_generated_headers_are_detected(head):
    assert is_generated(head) is True


def test_ordinary_source_is_not_generated():
    head = "namespace Pricing;\n\npublic static class NetCalculator\n{\n}"
    assert is_generated(head) is False


def test_generated_marker_is_matched_case_insensitively():
    assert is_generated("// CODE GENERATED BY TOOLING") is True


def test_generated_marker_below_the_header_window_is_ignored():
    head = "\n" * 40 + "// <auto-generated>"
    assert is_generated(head) is False


def test_generated_marker_within_the_header_window_is_detected():
    head = "\n" * 18 + "// <auto-generated>"  # marker text is on line 19
    assert is_generated(head) is True


def test_generated_marker_just_outside_the_header_window_is_ignored():
    head = "\n" * 20 + "// <auto-generated>"  # marker text is on line 21
    assert is_generated(head) is False


@pytest.mark.parametrize(
    "rel_path",
    [
        "vendor/acme/lib/Foo.php",
        "node_modules/left-pad/index.js",
        "src/Migrations/Version20250101.php",
        "web/assets/app.min.js",
        "src/__snapshots__/Widget.snap.js",
        "dist/bundle.js",
        "src/Mapper.generated.cs",
    ],
)
def test_paths_excluded_by_convention(rel_path):
    assert is_excluded_path(rel_path, include_tests=False) is True


@pytest.mark.parametrize(
    "rel_path",
    [
        "tests/test_pricing.py",
        "src/Pricing/NetCalculatorTest.cs",
        "spec/models/user_spec.rb",
        "src/__tests__/widget.test.ts",
        "src/pricing_test.py",
        "src/widget.spec.ts",
        "src/Pricing/NetCalculatorTests.cs",
        "src/widget.specs.ts",
    ],
)
def test_test_paths_excluded_unless_requested(rel_path):
    assert is_excluded_path(rel_path, include_tests=False) is True
    assert is_excluded_path(rel_path, include_tests=True) is False


def test_ordinary_source_path_is_kept():
    assert (
        is_excluded_path("src/Pricing/NetCalculator.cs", include_tests=False) is False
    )


@pytest.mark.parametrize(
    "rel_path",
    [
        "src/latest/Foo.cs",
        "lib/protest/x.rb",
        "src/contest/Entry.py",
        "app/Specimen.php",
        "src/redist/pack.js",
    ],
)
def test_words_containing_an_exclusion_term_are_not_excluded(rel_path):
    """A path segment or stem token only matching by substring must survive.

    ``latest``, ``protest`` and ``contest`` all end in ``test``; ``Specimen``
    starts with ``spec``; ``redist`` ends in ``dist``. None of them equal the
    exclusion term as a whole segment or token.
    """
    assert is_excluded_path(rel_path, include_tests=False) is False


@pytest.mark.parametrize(
    "rel_path",
    [
        "src/build/Builder.cs",
        "core/dist/x.py",
        "src/Pricing/NetCalculatorTest.cs",
        "web/__tests__/a.js",
    ],
)
def test_genuine_matches_stay_excluded(rel_path):
    """Boundary matching must not stop filtering real build output or tests.

    ``build`` and ``dist`` are whole path segments here, not substrings of a
    longer word, so they still match. The CamelCase suffix and the
    ``__tests__`` directory keep matching too.
    """
    assert is_excluded_path(rel_path, include_tests=False) is True


def test_short_file_is_a_single_chunk():
    assert chunk_plan(120) == [(1, 120)]


def test_file_exactly_at_the_limit_is_a_single_chunk():
    assert chunk_plan(800) == [(1, 800)]


def test_long_file_is_split_with_overlap():
    assert chunk_plan(900) == [(1, 800), (761, 900)]


def test_very_long_file_produces_consecutive_overlapping_chunks():
    assert chunk_plan(2000) == [(1, 800), (761, 1560), (1521, 2000)]


def test_empty_file_produces_no_chunks():
    assert chunk_plan(0) == []


def test_overlap_at_or_above_max_lines_is_rejected():
    with pytest.raises(ValueError, match=r"overlap.*max_lines"):
        chunk_plan(2000, max_lines=40, overlap=40)
