import subprocess
from pathlib import Path

import pytest
from inventory import build_inventory, list_source_files, main


def _git(repo: Path, *args: str) -> None:
    subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        capture_output=True,
    )


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "test@example.com")
    _git(tmp_path, "config", "user.name", "Test")

    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "calc.py").write_text("def net(x):\n    return x\n")
    (tmp_path / "src" / "gen.py").write_text(
        "# Code generated by tool. DO NOT EDIT.\nA = 1\n"
    )
    (tmp_path / "src" / "long.py").write_text("x = 1\n" * 900)
    (tmp_path / "src" / "blob.py").write_bytes(b"\xff\xfe\x00\x01")
    (tmp_path / "README.md").write_text("# readme\n")

    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "test_calc.py").write_text("def test_x():\n    pass\n")

    (tmp_path / "vendor").mkdir()
    (tmp_path / "vendor" / "lib.py").write_text("B = 2\n")

    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-q", "-m", "fixture")
    return tmp_path


def test_list_source_files_returns_tracked_paths(repo: Path):
    paths = list_source_files(repo)
    assert "src/calc.py" in paths
    assert "README.md" in paths


def test_build_inventory_keeps_ordinary_source(repo: Path):
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/calc.py" in kept


def test_build_inventory_drops_generated_tests_vendor_and_non_source(repo: Path):
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/gen.py" not in kept
    assert "tests/test_calc.py" not in kept
    assert "vendor/lib.py" not in kept
    assert "README.md" not in kept


def test_build_inventory_counts_each_exclusion_reason(repo: Path):
    inventory = build_inventory(repo)
    assert inventory["excluded"]["generated"] == 1
    assert inventory["excluded"]["path_rule"] == 2
    assert inventory["excluded"]["unsupported_extension"] == 1


def test_build_inventory_counts_unreadable_files_separately(repo: Path):
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/blob.py" not in kept
    assert inventory["excluded"]["unreadable"] == 1
    assert inventory["excluded"]["path_rule"] == 2


def test_build_inventory_chunks_long_files(repo: Path):
    inventory = build_inventory(repo)
    entry = next(e for e in inventory["files"] if e["path"] == "src/long.py")
    assert entry["lines"] == 900
    assert entry["chunks"] == [[1, 800], [761, 900]]


def test_build_inventory_records_language(repo: Path):
    inventory = build_inventory(repo)
    entry = next(e for e in inventory["files"] if e["path"] == "src/calc.py")
    assert entry["language"] == "python"


def test_include_tests_keeps_the_test_corpus(repo: Path):
    inventory = build_inventory(repo, include_tests=True)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "tests/test_calc.py" in kept


def test_totals_are_consistent_with_the_file_list(repo: Path):
    inventory = build_inventory(repo)
    assert inventory["totals"]["files"] == len(inventory["files"])
    assert inventory["totals"]["chunks"] == sum(
        len(e["chunks"]) for e in inventory["files"]
    )


def test_cli_writes_json_to_stdout(repo: Path, capsys):
    exit_code = main([str(repo)])
    assert exit_code == 0
    assert '"files"' in capsys.readouterr().out


def test_cli_rejects_a_path_that_is_not_a_git_repo(tmp_path: Path, capsys):
    exit_code = main([str(tmp_path)])
    assert exit_code == 1
    assert "not a git repository" in capsys.readouterr().err
