import json
import os
import subprocess
from pathlib import Path

import pytest
from inventory import build_inventory, list_source_files, main


def _git(repo: Path, *args: str) -> None:
    subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        capture_output=True,
    )


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "test@example.com")
    _git(tmp_path, "config", "user.name", "Test")

    (tmp_path / ".gitignore").write_text("*.pyc\n")

    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "calc.py").write_text("def net(x):\n    return x\n")
    (tmp_path / "src" / "gen.py").write_text(
        "# Code generated by tool. DO NOT EDIT.\nA = 1\n"
    )
    (tmp_path / "src" / "long.py").write_text("x = 1\n" * 900)
    (tmp_path / "src" / "blob.py").write_bytes(b"\xff\xfe\x00\x01")
    (tmp_path / "README.md").write_text("# readme\n")

    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "test_calc.py").write_text("def test_x():\n    pass\n")

    (tmp_path / "vendor").mkdir()
    (tmp_path / "vendor" / "lib.py").write_text("B = 2\n")

    # A dangling symlink (target never existed) and a file that is tracked
    # but has since been deleted from disk without `git rm` -- both everyday
    # mid-rebase states, and both must not crash the inventory.
    (tmp_path / "src" / "dangling.py").symlink_to(
        tmp_path / "src" / "does-not-exist.py"
    )
    (tmp_path / "src" / "ghost.py").write_text("C = 3\n")

    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-q", "-m", "fixture")

    (tmp_path / "src" / "ghost.py").unlink()

    # Untracked and matched by the committed .gitignore above: must never
    # surface as an untracked source file. Only `--exclude-standard` on the
    # `git ls-files --others` call keeps it out.
    (tmp_path / "src" / "cache.pyc").write_text("compiled\n")

    return tmp_path


def test_list_source_files_returns_tracked_paths(repo: Path):
    paths = list_source_files(repo)
    assert "src/calc.py" in paths
    assert "README.md" in paths


def test_build_inventory_keeps_ordinary_source(repo: Path):
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/calc.py" in kept


def test_build_inventory_drops_generated_tests_vendor_and_non_source(repo: Path):
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/gen.py" not in kept
    assert "tests/test_calc.py" not in kept
    assert "vendor/lib.py" not in kept
    assert "README.md" not in kept


def test_build_inventory_counts_each_exclusion_reason(repo: Path):
    inventory = build_inventory(repo)
    assert inventory["excluded"]["generated"] == 1
    assert inventory["excluded"]["path_rule"] == 2
    # README.md (".md") and the tracked ".gitignore" (no extension).
    assert inventory["excluded"]["unsupported_extension"] == 2


def test_build_inventory_splits_unreadable_files_by_cause(repo: Path):
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/blob.py" not in kept
    assert "src/dangling.py" not in kept
    assert "src/ghost.py" not in kept
    # dangling.py is a symlink -- caught by the symlink bucket before any
    # read is attempted, dangling or not (see
    # test_build_inventory_puts_a_tracked_symlink_in_its_own_bucket). ghost.py
    # is tracked but deleted from disk -- a FileNotFoundError -> "missing".
    # blob.py is a bad encoding -> "undecodable". Neither triggers a
    # permission error here.
    assert inventory["excluded"]["missing"] == 1
    assert inventory["excluded"]["symlink"] == 1
    assert inventory["excluded"]["undecodable"] == 1
    assert inventory["excluded"]["permission_denied"] == 0
    assert inventory["excluded"]["path_rule"] == 2
    assert inventory["excluded_paths"]["missing"] == ["src/ghost.py"]
    assert inventory["excluded_paths"]["symlink"] == ["src/dangling.py"]
    assert inventory["excluded_paths"]["undecodable"] == ["src/blob.py"]
    assert inventory["excluded_paths"]["permission_denied"] == []


def test_build_inventory_puts_a_tracked_symlink_in_its_own_bucket(repo: Path):
    # A tracked symlink pointing at another tracked file must not be
    # inventoried as a second copy of that file's content -- and calc.py
    # itself must still be inventoried exactly once, not skipped because its
    # content is also reachable through the alias. The fixture's own
    # src/dangling.py is already a (dangling) symlink, so the count is 2, not
    # 1 -- see test_build_inventory_splits_unreadable_files_by_cause.
    (repo / "src" / "alias.py").symlink_to("calc.py")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "add a symlink alias")
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/alias.py" not in kept
    assert "src/calc.py" in kept
    assert inventory["excluded"]["symlink"] == 2
    assert sorted(inventory["excluded_paths"]["symlink"]) == [
        "src/alias.py",
        "src/dangling.py",
    ]


def test_build_inventory_puts_a_gitlink_in_its_own_submodule_bucket(repo: Path):
    # A gitlink (a submodule reference, git tree mode 160000) is faked with
    # low-level plumbing -- a real `git submodule add` needs a fetchable
    # remote, which a throwaway fixture repo does not have.
    fake_commit_sha = "a" * 40
    _git(
        repo,
        "update-index",
        "--add",
        "--cacheinfo",
        f"160000,{fake_commit_sha},external-lib",
    )
    _git(repo, "commit", "-q", "-m", "add a submodule reference")
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "external-lib" not in kept
    assert inventory["excluded"]["submodule"] == 1
    assert inventory["excluded_paths"]["submodule"] == ["external-lib"]
    # A gitlink must not also inflate the unsupported-extension histogram's
    # no-extension bucket -- that bucket is for genuine extensionless
    # source (Makefile, Dockerfile, a shebang script), not gitlinks. The
    # fixture's own tracked .gitignore already accounts for the single
    # "(no extension)" entry; the gitlink must not add a second.
    assert inventory["unsupported_extensions"]["(no extension)"] == 1


def test_totals_tracked_accounts_for_every_tracked_file(repo: Path):
    # Every file list_source_files() returns must land in exactly one place:
    # the kept files list, or one exclusion bucket. untracked is excluded
    # from the sum on purpose -- it comes from a separate git invocation
    # entirely and was never part of the tracked set totals.tracked counts.
    inventory = build_inventory(repo)
    accounted = inventory["totals"]["files"] + sum(
        count
        for reason, count in inventory["excluded"].items()
        if reason != "untracked"
    )
    assert inventory["totals"]["tracked"] == accounted


@pytest.mark.skipif(
    hasattr(os, "geteuid") and os.geteuid() == 0,
    reason="root bypasses file permission checks",
)
def test_build_inventory_reports_permission_denied_files(repo: Path):
    secret = repo / "src" / "secret.py"
    secret.write_text("E = 5\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "add unreadable file")
    secret.chmod(0o000)
    try:
        inventory = build_inventory(repo)
        assert inventory["excluded"]["permission_denied"] == 1
        assert inventory["excluded_paths"]["permission_denied"] == ["src/secret.py"]
    finally:
        secret.chmod(0o644)


def test_build_inventory_tracks_unsupported_extension_histogram(repo: Path):
    inventory = build_inventory(repo)
    # The tracked ".gitignore" has no extension -- rendered as the literal
    # label "(no extension)" rather than an empty-string key, distinct from
    # the dedicated "submodule" bucket a gitlink lands in instead (see
    # test_build_inventory_puts_a_gitlink_in_its_own_submodule_bucket).
    assert inventory["unsupported_extensions"] == {".md": 1, "(no extension)": 1}


def test_build_inventory_histogram_counts_repeated_unsupported_extensions(
    repo: Path,
):
    second_md = repo / "docs.md"
    second_md.write_text("# docs\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "add second markdown file")
    inventory = build_inventory(repo)
    assert inventory["unsupported_extensions"] == {".md": 2, "(no extension)": 1}


def test_build_inventory_records_generated_paths(repo: Path):
    inventory = build_inventory(repo)
    assert inventory["excluded_paths"]["generated"] == ["src/gen.py"]


def test_build_inventory_counts_untracked_source_files(repo: Path):
    (repo / "src" / "wip.py").write_text("D = 4\n")
    inventory = build_inventory(repo)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "src/wip.py" not in kept
    assert inventory["excluded"]["untracked"] == 1
    assert inventory["excluded_paths"]["untracked"] == ["src/wip.py"]
    # Untracked files must not perturb the tracked-file counters.
    assert inventory["excluded"]["path_rule"] == 2


def test_build_inventory_ignores_gitignored_files_when_counting_untracked(
    repo: Path,
):
    # The fixture's own src/cache.pyc is untracked and matched by the
    # committed .gitignore's "*.pyc" rule. Only `--exclude-standard` on the
    # `git ls-files --others` call keeps a gitignored file out of the
    # untracked bucket -- without it, every gitignored file in the tree would
    # be reported as an untracked source file.
    inventory = build_inventory(repo)
    assert inventory["excluded"]["untracked"] == 0
    assert inventory["excluded_paths"]["untracked"] == []


def test_build_inventory_chunks_long_files(repo: Path):
    inventory = build_inventory(repo)
    entry = next(e for e in inventory["files"] if e["path"] == "src/long.py")
    assert entry["lines"] == 900
    assert entry["chunks"] == [[1, 800], [761, 900]]


def test_build_inventory_records_language(repo: Path):
    inventory = build_inventory(repo)
    entry = next(e for e in inventory["files"] if e["path"] == "src/calc.py")
    assert entry["language"] == "python"


def test_build_inventory_normalises_extension_case(repo: Path):
    widget = repo / "src" / "Widget.CS"
    widget.write_text("public class Widget {}\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "add upper-case extension file")
    inventory = build_inventory(repo)
    kept = {entry["path"]: entry for entry in inventory["files"]}
    assert "src/Widget.CS" in kept
    assert kept["src/Widget.CS"]["language"] == "csharp"


def test_include_tests_keeps_the_test_corpus(repo: Path):
    inventory = build_inventory(repo, include_tests=True)
    kept = {entry["path"] for entry in inventory["files"]}
    assert "tests/test_calc.py" in kept


def test_build_inventory_reports_an_absolute_repo_path(repo: Path):
    # Stage 1 joins the relative file paths it returns onto this field for
    # subagents that share no working directory with this process -- a
    # relative value here would break every one of those downstream reads.
    # A relative Path argument makes str(repo) and str(repo.resolve())
    # diverge, which a bare tmp_path (already absolute) cannot.
    relative_repo = Path(os.path.relpath(repo))
    inventory = build_inventory(relative_repo)
    assert Path(inventory["repo"]).is_absolute()
    assert inventory["repo"] == str(repo.resolve())


def test_build_inventory_reports_the_include_tests_flag_it_was_given(repo: Path):
    assert build_inventory(repo, include_tests=False)["include_tests"] is False
    assert build_inventory(repo, include_tests=True)["include_tests"] is True


def test_totals_are_consistent_with_the_file_list(repo: Path):
    # Fixture's only kept files are src/calc.py (2 lines, 1 chunk) and
    # src/long.py (900 lines, chunked as [1, 800] and [761, 900] -- see
    # test_build_inventory_chunks_long_files). Asserted as literal constants,
    # not recomputed from the implementation's own output, so a wrong sum
    # cannot mark its own homework.
    inventory = build_inventory(repo)
    assert inventory["totals"]["files"] == 2
    assert inventory["totals"]["lines"] == 902
    assert inventory["totals"]["chunks"] == 3


def test_cli_writes_json_to_stdout(repo: Path, capsys):
    exit_code = main([str(repo)])
    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out)
    assert isinstance(payload["files"], list)
    assert any(entry["path"] == "src/calc.py" for entry in payload["files"])


def test_cli_include_tests_flag_keeps_the_test_corpus(repo: Path, capsys):
    exit_code = main([str(repo), "--include-tests"])
    assert exit_code == 0
    payload = json.loads(capsys.readouterr().out)
    kept = {entry["path"] for entry in payload["files"]}
    assert "tests/test_calc.py" in kept


def test_cli_rejects_a_path_that_is_not_a_git_repo(tmp_path: Path, capsys):
    exit_code = main([str(tmp_path)])
    assert exit_code == 1
    assert "not a git repository" in capsys.readouterr().err
