"""Deterministic source-file inventory for semantic twin detection.

Stage 1 of the pipeline. Enumerates the source files worth summarising and
plans how to chunk the long ones. Standard library only.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

SOURCE_EXTENSIONS: dict[str, str] = {
    ".c": "c",
    ".cpp": "cpp",
    ".cs": "csharp",
    ".go": "go",
    ".h": "c",
    ".hpp": "cpp",
    ".java": "java",
    ".js": "javascript",
    ".jsx": "javascript",
    ".kt": "kotlin",
    ".php": "php",
    ".py": "python",
    ".rb": "ruby",
    ".rs": "rust",
    ".scala": "scala",
    ".swift": "swift",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".vue": "vue",
}

GENERATED_MARKERS = (
    "<auto-generated",
    "code generated by",
    "@generated",
    "do not edit",
)

GENERATED_HEADER_LINES = 20

EXCLUDED_PATH_SEGMENTS = (
    "vendor",
    "node_modules",
    "migrations",
    "__snapshots__",
    "dist",
    "build",
)

EXCLUDED_SUFFIXES = (".min.js", ".generated.cs")

TEST_PATH_SEGMENTS = ("tests", "test", "spec", "__tests__")

TEST_NAME_MARKERS = ("test", "tests", "spec", "specs")

# Exclusion reasons that also get a per-path list in excluded_paths, in
# addition to their count in excluded. Every other key in excluded (e.g.
# path_rule, unsupported_extension) is an aggregate count only -- there is
# no single file to name for a whole extension bucket or naming-convention
# rule. build_inventory derives both excluded and excluded_paths from this
# one tuple, so a future exclusion reason wired into one and forgotten in
# the other is no longer possible.
EXCLUSION_REASONS_WITH_PATHS = (
    "generated",
    "symlink",
    "submodule",
    "untracked",
    "missing",
    "undecodable",
    "permission_denied",
)


def is_generated(head: str) -> bool:
    """True when the first lines carry a generated-code marker."""
    window = "\n".join(head.splitlines()[:GENERATED_HEADER_LINES]).lower()
    return any(marker in window for marker in GENERATED_MARKERS)


def _looks_like_test(rel_path: str) -> bool:
    segments = rel_path.lower().split("/")
    if any(segment in TEST_PATH_SEGMENTS for segment in segments):
        return True
    # CamelCase suffix convention, checked against the unmodified stem before
    # lower-casing: NetCalculatorTest.cs is a test file, latest.py is not.
    stem = Path(rel_path).stem
    if stem.endswith(("Test", "Tests")):
        return True
    tokens = re.split(r"[._-]", stem.lower())
    return any(token in TEST_NAME_MARKERS for token in tokens)


def is_excluded_path(rel_path: str, include_tests: bool) -> bool:
    """True when a path is excluded by convention rather than by content."""
    segments = rel_path.lower().split("/")
    if any(segment in EXCLUDED_PATH_SEGMENTS for segment in segments):
        return True
    if rel_path.lower().endswith(EXCLUDED_SUFFIXES):
        return True
    return not include_tests and _looks_like_test(rel_path)


def chunk_plan(
    line_count: int, max_lines: int = 800, overlap: int = 40
) -> list[tuple[int, int]]:
    """Split a file into 1-based inclusive line ranges that overlap at the seams."""
    if overlap >= max_lines:
        raise ValueError(
            f"overlap ({overlap}) must be smaller than max_lines ({max_lines}), "
            "or the chunk boundary never advances"
        )
    if line_count <= 0:
        return []
    chunks: list[tuple[int, int]] = []
    start = 1
    while start <= line_count:
        end = min(start + max_lines - 1, line_count)
        chunks.append((start, end))
        if end == line_count:
            break
        start = end - overlap + 1
    return chunks


def list_source_files(repo: Path) -> list[str]:
    """Every path git tracks under `repo`, relative to the directory passed.

    `git -C <dir> ls-files` is scoped to the subtree under `<dir>` -- it
    does not list everything the repository as a whole tracks, only what
    sits under that directory -- and the paths it returns are relative to
    `<dir>`, not to the repository root. Both only coincide with "the whole
    repository" when `repo` *is* the root.
    """
    result = subprocess.run(
        ["git", "-C", str(repo), "ls-files", "-z"],
        capture_output=True,
        text=True,
        check=True,
    )
    return [path for path in result.stdout.split("\0") if path]


def list_untracked_files(repo: Path) -> list[str]:
    """Every untracked, non-ignored path under `repo`, same subtree scoping
    and path semantics as `list_source_files`."""
    result = subprocess.run(
        ["git", "-C", str(repo), "ls-files", "-z", "--others", "--exclude-standard"],
        capture_output=True,
        text=True,
        check=True,
    )
    return [path for path in result.stdout.split("\0") if path]


def list_submodule_paths(repo: Path) -> set[str]:
    """Every path git tracks as a gitlink (a submodule reference, tree mode
    160000) under `repo`, same subtree scoping and path semantics as
    `list_source_files`.

    A gitlink has no blob content of its own to read -- it names a commit in
    another repository -- and its `Path(...).suffix` is always empty, so it
    must be identified from the index itself rather than by trying to read
    it like an ordinary file.
    """
    result = subprocess.run(
        ["git", "-C", str(repo), "ls-files", "-z", "--stage"],
        capture_output=True,
        text=True,
        check=True,
    )
    submodules: set[str] = set()
    for entry in result.stdout.split("\0"):
        if not entry:
            continue
        metadata, _, path = entry.partition("\t")
        mode = metadata.split(" ", 1)[0]
        if mode == "160000":
            submodules.add(path)
    return submodules


def build_inventory(repo: Path, include_tests: bool = False) -> dict:
    """Inventory the source files worth summarising, with a chunking plan.

    Returns a dict with keys ``repo`` (the repository's absolute path),
    ``include_tests``, ``files`` (the kept entries: ``path``, ``language``,
    ``lines``, ``chunks``), ``excluded`` (a count per exclusion reason),
    ``excluded_paths`` (the paths behind each reason listed in
    `EXCLUSION_REASONS_WITH_PATHS`), ``unsupported_extensions`` (a histogram
    of the extensions responsible for the ``unsupported_extension`` count),
    and ``totals`` (``tracked``, ``files``, ``lines``, ``chunks``).
    """
    files: list[dict] = []
    excluded = {
        "path_rule": 0,
        "unsupported_extension": 0,
        **{reason: 0 for reason in EXCLUSION_REASONS_WITH_PATHS},
    }
    excluded_paths: dict[str, list[str]] = {
        reason: [] for reason in EXCLUSION_REASONS_WITH_PATHS
    }
    unsupported_extensions: dict[str, int] = {}

    # Untracked files are a branch-in-progress's most common state, not an
    # edge case. They are counted and named, never inventoried: silently
    # summarising code outside the repository's committed state would be a
    # different surprise than the one this bucket exists to prevent.
    untracked = list_untracked_files(repo)
    excluded["untracked"] = len(untracked)
    excluded_paths["untracked"] = untracked

    submodule_paths = list_submodule_paths(repo)
    tracked_paths = list_source_files(repo)

    for rel_path in tracked_paths:
        # A gitlink names a commit in another repository, not a blob in this
        # one -- there is no content to read, and its Path(...).suffix is
        # always empty, so it must be diverted before the extension check
        # would otherwise misfile it as just another extensionless file.
        if rel_path in submodule_paths:
            excluded["submodule"] += 1
            excluded_paths["submodule"].append(rel_path)
            continue

        suffix = Path(rel_path).suffix.lower()
        language = SOURCE_EXTENSIONS.get(suffix)
        if language is None:
            excluded["unsupported_extension"] += 1
            label = suffix if suffix else "(no extension)"
            unsupported_extensions[label] = unsupported_extensions.get(label, 0) + 1
            continue
        if is_excluded_path(rel_path, include_tests):
            excluded["path_rule"] += 1
            continue

        # A tracked symlink duplicates whatever it points at: reading
        # through it would inventory the same lines a second time under a
        # second path (or, for a link that escapes the repository, foreign
        # code as if it were repository source). It is counted and named,
        # never followed.
        if (repo / rel_path).is_symlink():
            excluded["symlink"] += 1
            excluded_paths["symlink"].append(rel_path)
            continue

        try:
            text = (repo / rel_path).read_text(encoding="utf-8")
        except FileNotFoundError:
            # A file that is tracked but has since been deleted from disk
            # without `git rm` -- an everyday mid-rebase state. The path is
            # tracked but has no content.
            excluded["missing"] += 1
            excluded_paths["missing"].append(rel_path)
            continue
        except PermissionError:
            excluded["permission_denied"] += 1
            excluded_paths["permission_denied"].append(rel_path)
            continue
        except UnicodeDecodeError:
            excluded["undecodable"] += 1
            excluded_paths["undecodable"].append(rel_path)
            continue
        except OSError:
            # Any other OS-level failure (e.g. a broken device or an I/O
            # error) is treated like a missing file: the content could not
            # be obtained.
            excluded["missing"] += 1
            excluded_paths["missing"].append(rel_path)
            continue

        if is_generated(text):
            excluded["generated"] += 1
            excluded_paths["generated"].append(rel_path)
            continue

        line_count = len(text.splitlines())
        files.append(
            {
                "path": rel_path,
                "language": language,
                "lines": line_count,
                "chunks": [list(chunk) for chunk in chunk_plan(line_count)],
            }
        )

    return {
        "repo": str(repo.resolve()),
        "include_tests": include_tests,
        "files": files,
        "excluded": excluded,
        "excluded_paths": excluded_paths,
        "unsupported_extensions": unsupported_extensions,
        "totals": {
            "tracked": len(tracked_paths),
            "files": len(files),
            "lines": sum(entry["lines"] for entry in files),
            "chunks": sum(len(entry["chunks"]) for entry in files),
        },
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Inventory a repository's source files for semantic twin detection."
    )
    parser.add_argument("repo", help="path to the git repository to inventory")
    parser.add_argument(
        "--include-tests",
        action="store_true",
        help="inventory the test corpus instead of skipping it",
    )
    args = parser.parse_args(argv)

    repo = Path(args.repo)
    probe = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--is-inside-work-tree"],
        capture_output=True,
        text=True,
        check=False,
    )
    if probe.returncode != 0:
        print(f"{repo} is not a git repository", file=sys.stderr)
        return 1

    json.dump(build_inventory(repo, args.include_tests), sys.stdout, indent=2)
    print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
